Slava test branch
tomomoto/Meeter_AndroidClient pull request #10
Opened 2019-03-14 21:45 UTC by Fafan2008

First PR

2019-03-14 21:48 UTC, tomomoto commented
@Fafan2008 
Nice one!
Please, dont merge (I am trying to fix /gradle and travis)

2019-03-14 21:48 UTC, tomomoto commented on .gitignore
> +gradle/wrapper/gradle-wrapper.properties
@Fafan2008 
Seems we dont really need to ignore them.
Fixing.

2019-03-14 22:47 UTC, tomomoto commented
@Fafan2008 This PR is no longer actual.
The required folder gradle was added in https://github.com/tomomoto/Meeter_AndroidClient/pull/9
In no longer ignored by .gitignore.
Take a look for super build:  
https://github.com/tomomoto/Meeter_AndroidClient/pull/9/checks

2019-03-14 23:17 UTC, tomomoto commented
@Fafan2008 
By the way, you could change ignoring gradle folder to .gradle and we can merge this PR ;)

2019-03-16 18:47 UTC, tomomoto commented on .gitignore
> +.gradle/4.10.1/fileChanges/last-build.bin
@Fafan2008 
Why do we need to ignore every file?
We can ignore the whole folder)

2019-03-16 18:48 UTC, tomomoto commented
@Fafan2008 Please fix ignoring the whole folder, not a signle file.

2019-03-16 18:48 UTC, tomomoto approved these changes

2019-03-16 19:20 UTC, tomomoto commented on AndroidClient/src/main/res/layout/activity_main.xml
> +        <ImageButton
@Fafan2008 Do we need a handler to this button click?

2019-03-16 19:21 UTC, tomomoto requested changes
Look at the questions please

2019-03-16 19:35 UTC, tomomoto commented on .gitignore
> +gradle/wrapper/gradle-wrapper.properties
@Fafan2008 Please, remove gradle folder from gitignore since we need this for travis..

2019-03-16 21:30 UTC, tomomoto commented on .gitignore
> +.gradle/*
@Fafan2008 Nice change.

2019-06-14 14:46 UTC, malltshik commented
Говорите по русске, yoba!

2025-06-13 19:49 UTC, closed without merging